<?php if(Register::getUserId()): ?>
    <form METHOD="post" action="/push">
        <div class="form-group">
            <label for="exampleInputEmail1">Comment</label>
            <textarea class="form-control" rows="3" name="text"></textarea>

        </div>
        <button type="submit" class="btn btn-success">Add new comment</button>
    </form>
    <hr>
<?php endif;?>

<h2>comments:</h2>

<?php
$comments = $this->comments;
if($comments) {
    renderTree($comments);
} else {
    echo '<p>No comments</p>';
}

function renderTree($arr, $level=0) {
    $prepend = str_repeat(' ', $level);

    echo $prepend, '<div style="padding-left: 20px;">';

    foreach($arr as $comment) { ?>

        <div class="media">
            <p class="pull-right"><small><?= date("F j, Y, g:i a", $comment['created_at']);?></small></p>
            <a class="media-left" href="#">
                <img src="images/images.jpg">
            </a>
            <div class="media-body">
                <h4 class="media-heading user_name"><?= $comment['username']?></h4>
                <p><?= $comment['text']?></p>
                <?php if(Register::getUserId()) :?>
                    <div class="btn-group btn-group-xs" role="group" aria-label="...">
                        <?php if(Register::getUserId() != $comment['user_id']): ?>
                            <button type="button" class="btn btn-primary reply-button">Reply</button>
                        <?php endif;?>
                        <?php if(Register::getUserId() == $comment['user_id']): ?>
                            <a type="button" class="btn btn-info update-button">Update</a>
                            <form action="/delete" method="post" class="btn-group btn-group-xs">
                                <input type="hidden" name="id" value="<?= $comment['id']?>">
                                <button type="submit" class="btn btn-danger">delete</button>
                            </form>

                        <?php endif;?>
                    </div>
                    <div class="col-md-12 reply-form hide-block">
                        <form METHOD="post" action="/reply">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Reply</label>
                                <textarea class="form-control" rows="3" name="text"></textarea>
                                <input type="hidden" name="parent" value="<?= $comment['id']?>">
                            </div>

                            <button type="submit" class="btn btn-success">Submit</button>
                        </form>
                    </div>
                <?php endif;?>

                <?php if(Register::getUserId() == $comment['user_id']): ?>
                    <div class="col-md-12 update-form hide-block">
                        <form METHOD="post" action="/update">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Update</label>
                                <textarea class="form-control" rows="3" name="text" ><?= $comment['text']?></textarea>
                                <input type="hidden" name="id" value="<?= $comment['id']?>">
                            </div>

                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
                    </div>
                <?php endif;?>
            </div>

        </div>

      <?php  if ( !empty($comment['child']) ) {
            renderTree($comment['child'], $level+1);
      }
    }

    echo $prepend, '</div>';
}

?>
